var qs={
"sunday":"星期日",
"monday":"星期一",
"tuesday":"星期二",
"wednesday":"星期三",
"thursday":"星期四",
"friday":"星期五",
"saturday":"星期六",
"fat":"胖",
"thin":"瘦",
"map":"地圖",
"chicken":"雞",
"hen":"母雞",
"cow":"牛",
"zebra":"斑馬",
"finger":"手指",
"cola":"可樂",
"hat":"帽子",
"face":"臉",
"bee":"蜜蜂",
"goat":"山羊",
"cherry":"櫻桃",
"drink":"飲料",
"beef":"牛肉",
"ant":"螞蟻",
"chocolate":"巧克力",
"noodle":"麵",
"sandwich":"三明治",
"soda":"汽水",
"soup":"湯",
"water":"水",
"room":"房間",
"toy":"玩具",
"volleyball":"排球",
"friend":"朋友",
"corn":"玉米",
"airplane":"飛機",
"coat":"大衣",
"boot":"靴子",
"computer":"電腦",
"eason":"陳昱瀚"
};

var qks = Object.keys(qs);
var qvs = Object.values(qs);
var qlst = Array.from({ length: qks.length }, (v, k) => k ); // [0,1,2,3,...,9]
